"""HydroWatch — export the standalone student forest to C for MCU inference.

Quantizes every tree to uint8 comparisons: feature values and split
thresholds are mapped through a per-feature affine transform over the
training-data range, so sklearn's `feature < threshold` becomes
`q < q_threshold` with no floating point in the tree walk. Leaf class
counts are stored scaled to 0..255 as int16 (int8 would overflow at 128+); prediction = argmax of summed
per-tree votes, first-index-wins — identical tie-breaking to sklearn.

Output: firmware/model.h — one self-contained header exposing
  HW_MODEL_predict(const float f[HW_FEATURE_COUNT], int votes_out[4]) -> class

The exported model is validated in Python by replaying the exact quantized
traversal and comparing against sklearn's predictions on fresh test draws.
"""

from __future__ import annotations

import os

import numpy as np
from joblib import load

import sensor_sim

MODEL_DIR = "model"
OUT_PATH = os.path.join("firmware", "model.h")
N_CLASSES = 4


def training_ranges():
    """Per-feature min/max over the training distribution (same seed)."""
    Xtr, _ = sensor_sim.make_dataset(scenarios_per_class=300)
    lo = Xtr.min(axis=0).astype(np.float64)
    hi = np.maximum(Xtr.max(axis=0).astype(np.float64), lo + 1e-6)
    return lo, hi


def main() -> None:
    model = load(os.path.join(MODEL_DIR, "student_standalone.joblib"))
    lo, hi = training_ranges()
    inv_scale = 255.0 / (hi - lo)          # q = (x - lo) * inv_scale
    scale = (hi - lo) / 255.0              # for validation replay
    n_feat = len(sensor_sim.FEATURE_ORDER)
    n_trees = len(model.estimators_)
    print(f"student_standalone: {n_trees} trees, depth "
          f"{max(e.get_depth() for e in model.estimators_)}, {n_feat} features")

    # ---- Flatten all trees; per-node feature index, uint8 thresholds ----
    child_left, child_right, feat_idx, thr_q, votes = [], [], [], [], []
    offsets = []
    for est in model.estimators_:
        t = est.tree_
        offsets.append(len(child_left))
        for i in range(t.node_count):
            if t.children_left[i] == -1:                     # leaf
                child_left.append(-1)
                child_right.append(-1)
                feat_idx.append(0)
                thr_q.append(0)
                c = np.clip(t.value[i, 0, :] * 255.0 / max(1.0, t.value[i, 0, :].sum()),
                            0, 255).astype(np.int64)
                votes.extend(int(x) for x in c)
            else:                                            # split
                f = int(t.feature[i])
                child_left.append(int(t.children_left[i]))
                child_right.append(int(t.children_right[i]))
                feat_idx.append(f)
                thr_q.append(int(np.clip(np.round((float(t.threshold[i]) - lo[f])
                                                  / scale[f]), 0, 255)))
                votes.extend([0] * N_CLASSES)

    # ---- Emit C ---------------------------------------------------------
    def arr(name, ctype, rows, per_line=12):
        body = []
        for r in rows:
            body.append("  " + ", ".join(str(x) for x in r) + ",")
        return (f"static const {ctype} {name}[] = {{\n"
                + "\n".join(body) + "\n};\n")

    L = []
    A = L.append
    A("/* Auto-generated by export_model.py — do not edit by hand.")
    A(" * Quantized standalone student random forest for on-MCU flood classification.")
    A(f" * Trees: {n_trees}  Features: {n_feat}  Classes: {N_CLASSES}")
    A(f" * Classes: {', '.join(sensor_sim.CLASS_NAMES)}")
    A(" */")
    A("#pragma once")
    A("")
    A(f"#define HW_FEATURE_COUNT {n_feat}")
    A(f"#define HW_TREE_COUNT {n_trees}")
    A(f"#define HW_CLASS_COUNT {N_CLASSES}")
    A("")
    A("/* Quantization: q = clip(round((x - LO) * INV_SCALE), 0, 255) */")
    A("static const float HW_FEAT_LO[HW_FEATURE_COUNT] = {")
    A("  " + ", ".join(f"{v:.4f}f" for v in lo) + ",")
    A("};")
    A("static const float HW_FEAT_INV_SCALE[HW_FEATURE_COUNT] = {")
    A("  " + ", ".join(f"{v:.6f}f" for v in inv_scale) + ",")
    A("};")
    A("")
    L.append(arr("HW_CHILD_LEFT", "int16_t",
                 [child_left[o:o + 16] for o in range(0, len(child_left), 16)]))
    L.append(arr("HW_CHILD_RIGHT", "int16_t",
                 [child_right[o:o + 16] for o in range(0, len(child_right), 16)]))
    L.append(arr("HW_FEATURE_IDX", "uint8_t",
                 [feat_idx[o:o + 24] for o in range(0, len(feat_idx), 24)]))
    L.append(arr("HW_THRESHOLD", "uint8_t",
                 [thr_q[o:o + 24] for o in range(0, len(thr_q), 24)]))
    L.append(arr("HW_LEAF_VOTES", "int16_t",
                 [votes[o:o + N_CLASSES] for o in range(0, len(votes), N_CLASSES)]))
    L.append(arr("HW_TREE_OFFSET", "int16_t", [offsets]))
    A("""
/* Predict flood regime from float features using uint8 comparisons only.
 * classes: 0=normal 1=rain_approach 2=flood_rise 3=debris_impact
 * Returns argmax class; per-class vote sums written to votes_out if non-NULL.
 */
static inline int HW_MODEL_predict(const float f[HW_FEATURE_COUNT],
                                   int votes_out[HW_CLASS_COUNT]) {
  uint8_t q[HW_FEATURE_COUNT];
  for (int i = 0; i < HW_FEATURE_COUNT; ++i) {
    int qi = (int)((f[i] - HW_FEAT_LO[i]) * HW_FEAT_INV_SCALE[i] + 0.5f);
    q[i] = qi < 0 ? 0u : (qi > 255 ? 255u : (uint8_t)qi);
  }
  int votes[HW_CLASS_COUNT] = {0, 0, 0, 0};
  for (int t = 0; t < HW_TREE_COUNT; ++t) {
    int base = HW_TREE_OFFSET[t];
    int node = 0;
    while (HW_CHILD_LEFT[base + node] >= 0) {
      node = (q[HW_FEATURE_IDX[base + node]] < HW_THRESHOLD[base + node])
               ? HW_CHILD_LEFT[base + node]
               : HW_CHILD_RIGHT[base + node];
    }
    const int16_t *v = &HW_LEAF_VOTES[(base + node) * HW_CLASS_COUNT];
    for (int c = 0; c < HW_CLASS_COUNT; ++c) votes[c] += v[c];
  }
  int best = 0;
  for (int c = 1; c < HW_CLASS_COUNT; ++c) if (votes[c] > votes[best]) best = c;
  if (votes_out) for (int c = 0; c < HW_CLASS_COUNT; ++c) votes_out[c] = votes[c];
  return best;
}
""")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as fh:
        fh.write("\n".join(L))
    print(f"wrote {OUT_PATH} ({os.path.getsize(OUT_PATH) / 1024:.1f} KB text)")

    # ---- Validate: replay the quantized C traversal against sklearn -----
    Xte, yte = sensor_sim.make_dataset(scenarios_per_class=40)
    sensor_sim.RNG = np.random.default_rng(777_001)
    Xte, yte = sensor_sim.make_dataset(scenarios_per_class=40)

    cl = np.array(child_left); cr = np.array(child_right)
    fi = np.array(feat_idx); tq = np.array(thr_q)
    vo = np.array(votes, dtype=np.int64).reshape(-1, N_CLASSES)
    offs = np.array(offsets)

    match, total, mism = 0, 0, []
    for row in range(0, Xte.shape[0], 5):
        total += 1
        q = np.clip(np.round((Xte[row] - lo) * inv_scale), 0, 255).astype(np.int64)
        acc = np.zeros(N_CLASSES, dtype=np.int64)
        for t in range(n_trees):
            node = 0
            base = offs[t]
            while cl[base + node] >= 0:
                node = cl[base + node] if q[fi[base + node]] < tq[base + node] \
                    else cr[base + node]
            acc += vo[base + node]
        c_pred = int(np.argmax(acc))          # first-max == C code == sklearn
        sk = int(model.predict(Xte[row:row + 1])[0])
        if c_pred == sk:
            match += 1
        else:
            mism.append((row, c_pred, sk))
    rate = match / total
    print(f"quantized traversal matches sklearn on {match}/{total} fresh test rows "
          f"({rate:.4f})")
    if mism:
        print("boundary disagreements (row, quantized, sklearn):", mism[:10])
        print("(a value within half a quantization step of a split threshold can round to the other branch; benign if rate >= 0.99)")
    if rate < 0.99:
        raise SystemExit(f"export validation FAILED: match rate {rate:.4f} < 0.99")
    print("export validated OK")


if __name__ == "__main__":
    main()
